### ISSUE TITLE
Guacamole VM access failed due to expired JWT token

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#1110]
**Describe the bug**
After using guacamole for a long period of time get:

`jwt.exceptions.ExpiredSignatureError: Signature has expired`

**Steps to reproduce**

1. Connect to a VM via Apache Guacamole.
2. Leave connection open for long period of time - 24hrs, then refresh the page.
3. Unable to access the VM. Even if refresh the page still unable to access the VM.

**Comment by tamirkamara** [comment]
Has this been resolved with the move to the oauth2-proxy?

**Comment by marrobi** [comment]
So still getting an issue, not sure if its the same, after time get in guacamole

```
022-04-21T09:49:37.499525747Z 09:49:37.498 [http-nio-8080-exec-3] WARN o.a.g.e.AuthenticationProviderFacade - The "azuretre" authentication provider has encountered an internal error which will halt the authentication process. If this is unexpected or you are the developer of this authentication provider, you may wish to enable debug-level logging. If this is expected and you wish to ignore such failures in the future, please set "skip-if-unavailable: azuretre" within your guacamole.properties.
2022-04-21T09:49:37.499535547Z 09:49:37.498 [http-nio-8080-exec-3] ERROR o.a.g.rest.RESTExceptionMapper - Request could not be processed: Exception getting VMs: A JSONObject text must begin with '{' at 1 [character 2 line 1]
2022-04-21T09:49:37.499543047Z 09:49:37.498 [http-nio-8080-exec-3] DEBUG o.a.g.rest.RESTExceptionMapper - Processing of request aborted by extension.
2022-04-21T09:49:37.499550747Z org.apache.guacamole.GuacamoleException: Exception getting VMs: A JSONObject text must begin with '{' at 1 [character 2 line 1]
2022-04-21T09:49:37.499557247Z at org.apache.guacamole.auth.azuretre.connection.ConnectionService.getConfigurations(ConnectionService.java:94)
2022-04-21T09:49:37.499564647Z at org.apache.guacamole.auth.azuretre.connection.ConnectionService.getConnections(ConnectionService.java:49)
2022-04-21T09:49:37.499571747Z at org.apache.guacamole.auth.azuretre.user.UserContext.init(UserContext.java:80)
2022-04-21T09:49:37.499578348Z at org.apache.guacamole.auth.azuretre.AzureTREAuthenticationProvider.getUserContext(AzureTREAuthenticationProvider.java:82)
2022-04-21T09:49:37.499585848Z at org.apache.guacamole.auth.azuretre.AzureTREAuthenticationProvider.getUserContext(AzureTREAuthenticationProvider.java:34)
2022-04-21T09:49:37.499596548Z at org.apache.guacamole.extension.AuthenticationProviderFacade.getUserContext(AuthenticationProviderFacade.java:248)
```

In the API get:

```
2022-04-21T09:49:37.495135856Z INFO: 169.254.130.1:60781 - "GET /api/workspaces/bcbaf7f5-1831-4043-856e-102fa3b45b1e/workspace-services/66df6604-ac68-41cd-bee8-0e9e7e0f07ff/user-resources HTTP/1.1" 401 Unauthorized
```

If I look at the `x-auth-request-access-token` header when accessing /guacamole, the token has expired.

**Comment by marrobi** [comment]
Sorry, not on the latest code with refresh value. Will redeploy and test.

**Comment by marrobi** [comment]
Ok, on the new version I get a new token which has an expiry time beyond the current time. Great. 

Existing connections to VMs remain connected, great, But when visit /guacamole I still get an error.

```
2022-04-22T10:13:55.689566960Z DEBUG:root:Signature has expired
2022-04-22T10:13:55.689591460Z Signature has expired
```

I have verified the expiry of the token on the browser request is in the future.

Could the Guacamole code be still using the initial token?

**Comment by marrobi** [comment]
Looks like the access token is set in the ```AzureTREAuthenticatedUser``` class when the user logs in. This will go stale, and needs to be updated with the token in the client request.

**Comment by eladiw** [comment]
Checking. @anatbal
