### ISSUE TITLE
504 Gateway Time-out when we want to GET link after the draft export airlock request is created

### ISSUE THREAD

**Issue by dusan-ilic-mhra** [microsoft/AzureTRE#3240]
**Describe the bug**
In version v0.7.0 which is currently on our DEV environment, we get 504 Gateway Time-out every time when we:

1. create a draft export airlock request:
![image](https://user-images.githubusercontent.com/104429461/220608841-1dc3e31b-8229-4032-a61b-3ed6aee0e743.png)

2.  GET/api/workspaces/{workspace_id}/requests/{airlock_request_id}/link:
![image](https://user-images.githubusercontent.com/104429461/220608619-f3b8478f-9210-4645-8d78-cf85705ce056.png)

3. And, this is the log from App Service:
![image](https://user-images.githubusercontent.com/104429461/220609061-31016b8d-036d-4875-8173-75619b6a496d.png)
 
5. After that, the environment is unavailable for a while with 502 and 504 gateway errors.

**Steps to reproduce**

Explained above.

**Comment by dusan-ilic-mhra** [comment]
Hello @tamirkamara, @marrobi 

This is a blocker for us currently. 
Could you please help us to resolve this issue?

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara, @marrobi 

For the import airlock requests we are getting the link, this issue is happening only when we want to do an export.

**Comment by dusan-ilic-mhra** [comment]
@tamirkamara, @marrobi 

After digging more into app service logs we can see that connection to the airlock export storage account within the workspace is timing out:

![image](https://user-images.githubusercontent.com/104429461/220922464-871c5524-ef0f-49c8-bc92-add86ff961a5.png)


You can see the full log here:

[connection-time-out-storage-account-stalexintws99b6.txt](https://github.com/microsoft/AzureTRE/files/10813980/connection-time-out-storage-account-stalexintws99b6.txt)

Could you pelase advise?

**Comment by marrobi** [comment]
I believe this has been fixed in a more recent update -https://github.com/microsoft/AzureTRE/pull/3215

Sometimes the private link DNS records were not being created correctly.

@tamirkamara think this is the same issue?

**Comment by migldasilva** [comment]
@tamirkamara We have just applied the changes proposed by @marrobi in [this](https://github.com/microsoft/AzureTRE/issues/3240#issuecomment-1441818437) comment.

However we still have the timeout problem. 

I uploaded the full log in this comment.
[Log_Default_Docker.txt](https://github.com/microsoft/AzureTRE/files/10882156/Log_Default_Docker.txt)

**Comment by marrobi** [comment]
@migldasilva do you still hit this? It was resolved, and required changes detailed in the release notes. Thanks.

**Comment by migldasilva** [comment]
@marrobi We haven't noticed this issue for a while. Thanks for the clarification, I'll review the release notes.

**Comment by marrobi** [comment]
OK, I'll close the issue, if you see it again, let us know.
